dist: xenial

sudo: required

services:
  - docker

language: bash

env:
  global:
    - secure: hB8hVjR/Wf+9aDns1ISnatocZ3UlHD/+L+/qceQJKpNScEvUXSwrgvVuWTrVCaLCs+2vcNAeGNZgtBUcTHr5xgO+lX19R3KysivdrGJ2KBfBq6brYB7FcRVAAnkX3Tr4rzJG618AxspWG2DNL2e+LNN36fhmvh4uV/sR9rKPiIy1PDy2MpIpecPC5FYHvp0M+U2iFmmGgrqjy2KpGW/VXr6t8sWuo4Lu1fVbxlGYJ4BQH8XRv5Q1R2cTiG+EmVXqZEhGealToCWUTdoNvoULrN8wkewltvJuSqn6QcRe9dKmFxZgmsKFWb4o4cUKCCxkcUDMal/yUwP7n/FvRzSetI+AmTGupv7GWvNLaoVXd8F/0cfUhhZlA8IdcSkenitobC7BDrcLBw0N7J15twFA8M0H2R+ohqBSTPZGcKnb/gyi+R4RUcYea0yYzG3DP6MLDNskMW8SoxeILvL+ita3YLwGy+1TNc+ccsaphA5/y6JfYJN7hDzFy1F7ezrdxSO+GBfibuY6GIFqplLCsreA/fCTCrqrfdWWDB/ZTZu4aqWs+dvvjOaioxzTzUWak4uLEVVHC87p0uqo6a+ZrTMCR4MCk0dsSmvagNXmBttR1y45b2sYqDpN1gwW9t/NvaDJbbDFKELnXOIRXD7TPaqm8XuNn6X1qPLuFHfAAFwjsbE=
    - secure: ndNUMx+IZxPQeOr9rxnGmZZxg37O4NYVVH5sV75flwM1j8LXz7J/p51dJ/TeAONtwEk3MykR/2c4ok+8Gnu1cTZAY2U+Kpg0rCDlrTQA2lrsrPYayOyBH/FHlVtSJ2ItkRZJ3rv/xq1aGXuP4E+1/vT/OG7pRjtXW+bUIqgKKUiYb9T1S3DyMA9EZbBQGwX44H6JWjbd2A6lRvIvUsJ/CuQZzCcBZQw2+wO/zdY//gBtejPVIJso163J3XDQEjX8MNfBXSfkiEtd2Rf+z3/Le2GQAUmv3YZxXFENJpfZQwRRLZ1fo4/1LuqyneciYNWAhD+durJ2xKWbV6Ywk0xniADQ5iByU7rQ6z53Ed2DUUgQV6bj9ypib1aZvfWpaIQAwsnHolnh44cokHsyuNv6a2ouu0YlvFaQBFwEH0PxgF6KvRmvsF15GF+l0TNYJncFxfk/38MXuOqPMJ+y5O4eOPtWUQY0k2AKDBs4xnOl71FhACohroWH+Q+FussNqEx7TK5LyoCxiCMOYOp2lsDT5q+gNRwLyg89lVX/kCdLmVAVZMSP7RKSB2kyV37ufuou8Grkefjg95GqcRSChqReCAxstIxLySzalDHp0jm77cCwda68BpX353ypR7WKIWRRvr7vNouseaO2hCwQGeLnfPd1gcYfq+Q0gnDgG82Nds8=
  matrix:
    - ARCH="amd64" IMAGE="ttrss"
    - ARCH="arm32v6" IMAGE="ttrss-arm32v6"

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - curl -SLO https://github.com/multiarch/qemu-user-static/releases/download/v2.9.1-1/qemu-arm-static.tar.gz
  - tar zxvf qemu-arm-static.tar.gz
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then
    docker build -t nventiveux/${IMAGE}:latest -t nventiveux/${IMAGE}:stable -f Dockerfile.${ARCH} .;
    fi
  - docker images

after_script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker push nventiveux/${IMAGE}
  - docker logout
