FROM {{ ARCH + '/' if ARCH != 'amd64' else '' }}alpine:3.13

LABEL maintainers="Vincent BESANCON <besancon.vincent@gmail.com>"
{% if ARCH == 'arm32v6' %}
# Install static QEMU for ARM build from Travis CI
COPY qemu-arm-static /usr/bin/qemu-arm-static
{% endif %}
# TTRSS upstream commit reference
ARG TTRSS_COMMIT="master"

SHELL ["/bin/ash", "-eo", "pipefail", "-c"]

# Database connection
ENV \
    TTRSS_DB_HOST="database" \
    TTRSS_DB_NAME="ttrss" \
    TTRSS_DB_PASS="ttrss" \
    TTRSS_DB_PORT="5432" \
    TTRSS_DB_TYPE="pgsql" \
    TTRSS_DB_USER="ttrss" \
    TTRSS_DIGEST_SUBJECT="[rss] News headlines on last 24 hours" \
    TTRSS_PLUGINS="auth_internal,note,import_export" \
    TTRSS_SELF_URL_PATH="http://localhost:8000/" \
    TTRSS_SMTP_FROM_ADDRESS="noreply@mydomain.com" \
    TTRSS_SMTP_FROM_NAME="TT-RSS Feeds" \
    TTRSS_SMTP_LOGIN="" \
    TTRSS_SMTP_PASSWORD="" \
    TTRSS_SMTP_PORT="" \
    TTRSS_SMTP_SECURE="" \
    TTRSS_SMTP_SERVER=""

# Install directories
RUN mkdir -p /srv/ttrss /etc/nginx/ssl

# Install packages
RUN apk --update --no-cache add \
      ca-certificates=~20191127 \
      curl=~7.76 \
      gettext=~0.20 \
      git=~2.30 \
      libxslt=~1.1 \
      msmtp=~1.8 \
      netcat-openbsd=~1.130 \
      nginx=~1.18 \
      openssl=~1.1 \
      php8=~8.0 \
      php8-curl=~8.0 \
      php8-dom=~8.0 \
      php8-fileinfo=~8.0 \
      php8-fpm=~8.0 \
      php8-gd=~8.0 \
      php8-iconv=~8.0 \
      php8-intl=~8.0 \
      php8-mbstring=~8.0 \
      php8-mysqlnd=~8.0 \
      php8-opcache=~8.0 \
      php8-openssl=~8.0 \
      php8-pcntl=~8.0 \
      php8-pdo_mysql=~8.0 \
      php8-pdo_pgsql=~8.0 \
      php8-pgsql=~8.0 \
      php8-posix=~8.0 \
      php8-session=~8.0 \
      php8-tokenizer=~8.0 \
      php8-xsl=~8.0 \
      supervisor=~4.2 \
    && ln -sv /usr/bin/php8 /usr/bin/php \
    && curl -SL \
        https://git.tt-rss.org/git/tt-rss/archive/${TTRSS_COMMIT}.tar.gz \
        | tar xzC /srv/ttrss --strip-components 1 \
    && curl -SL \
        https://github.com/levito/tt-rss-feedly-theme/archive/master.tar.gz \
        | tar xzC /tmp \
          && cp -r /tmp/tt-rss-feedly-theme-master/feedly* /srv/ttrss/themes.local \
          && rm -rf /tmp/tt-rss-feedly-theme-master

# Install TT-RSS configuration
COPY ttrss/config.php /srv/ttrss/config.php

# Install msmtp client configuration template
COPY ttrss/msmtprc.tpl /var/tmp/msmtprc.tpl

# Fix permissions
RUN chown nginx:nginx -R /srv/ttrss

# Nginx configuration
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/conf.d/ttrss.conf /etc/nginx/conf.d/ttrss.conf
RUN rm /etc/nginx/conf.d/default.conf

# PHP / PHP-FPM configuration
COPY php8/php-fpm.d/*.conf /etc/php8/php-fpm.d/
COPY php8/conf.d/*.ini /etc/php8/conf.d/

# Listening ports
EXPOSE 80

# Persist data
VOLUME /srv/ttrss/cache /srv/ttrss/feed-icons

# Setup init
COPY supervisord.conf /supervisord.conf
COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
