FROM {{ ARCH + '/' if ARCH != 'amd64' else '' }}alpine:3.13

LABEL maintainers="Vincent BESANCON <besancon.vincent@gmail.com>"
{% if ARCH == 'arm32v6' %}
# Install static QEMU for ARM build from Travis CI
COPY qemu-arm-static /usr/bin/qemu-arm-static
{% endif %}
# TTRSS upstream commit reference
ARG TTRSS_COMMIT="master"

# Database connection
ENV \
    TTRSS_DB_HOST="database" \
    TTRSS_DB_NAME="ttrss" \
    TTRSS_DB_PASS="ttrss" \
    TTRSS_DB_PORT="5432" \
    TTRSS_DB_TYPE="pgsql" \
    TTRSS_DB_USER="ttrss" \
    TTRSS_DIGEST_SUBJECT="[rss] News headlines on last 24 hours" \
    TTRSS_PLUGINS="auth_internal,note,import_export" \
    TTRSS_SELF_URL_PATH="http://localhost:8000/" \
    TTRSS_SMTP_FROM_ADDRESS="noreply@mydomain.com" \
    TTRSS_SMTP_FROM_NAME="TT-RSS Feeds" \
    TTRSS_SMTP_LOGIN="" \
    TTRSS_SMTP_PASSWORD="" \
    TTRSS_SMTP_PORT="" \
    TTRSS_SMTP_SECURE="" \
    TTRSS_SMTP_SERVER=""

# Install directories
RUN mkdir -p /srv/ttrss /etc/nginx/ssl

# Install packages
RUN set -x \
      && apk --update --no-cache add \
        ca-certificates \
        curl            \
        gettext         \
        git             \
        msmtp           \
        netcat-openbsd  \
        nginx           \
        openssl         \
        php8            \
        php8-curl       \
        php8-dom        \
        php8-fileinfo   \
        php8-fpm        \
        php8-gd         \
        php8-iconv      \
        php8-intl       \
        php8-mbstring   \
        php8-mysqlnd    \
        php8-opcache    \
        php8-openssl    \
        php8-pcntl      \
        php8-pdo_mysql  \
        php8-pdo_pgsql  \
        php8-pgsql      \
        php8-posix      \
        php8-session    \
        supervisor      \
      && ln -sv /usr/bin/php8 /usr/bin/php \
      && curl -SL \
          https://git.tt-rss.org/git/tt-rss/archive/${TTRSS_COMMIT}.tar.gz \
          | tar xzC /srv/ttrss --strip-components 1 \
      && curl -SL \
          https://github.com/levito/tt-rss-feedly-theme/archive/master.tar.gz \
          | tar xzC /tmp \
            && cp -r /tmp/tt-rss-feedly-theme-master/feedly* /srv/ttrss/themes.local \
            && rm -rf /tmp/tt-rss-feedly-theme-master

# Install TT-RSS configuration
ADD ttrss/config.php /srv/ttrss/config.php

# Install msmtp client configuration template
ADD ttrss/msmtprc.tpl /var/tmp/msmtprc.tpl

# Fix permissions
RUN chown nginx:nginx -R /srv/ttrss

# Nginx configuration
ADD nginx/nginx.conf /etc/nginx/nginx.conf
ADD nginx/conf.d/ttrss.conf /etc/nginx/conf.d/ttrss.conf
RUN rm /etc/nginx/conf.d/default.conf

# PHP / PHP-FPM configuration
ADD php8/php-fpm.d/*.conf /etc/php8/php-fpm.d/
ADD php8/conf.d/*.ini /etc/php8/conf.d/

# Listening ports
EXPOSE 80

# Persist data
VOLUME /srv/ttrss/cache /srv/ttrss/feed-icons

# Setup init
ADD supervisord.conf /supervisord.conf
ADD entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
